baseURL:
  'https://balanice.github.io/'
languageCode:
  'en-us'
title:
  "Balanice's Blog"
theme:
  "hyde"
Menus:
  main:
    - Name: "balanice"
      URL: "https://github.com/balanice/"

params:
  description:
    "资深 Ctrl C + Ctrl V 程序员"
  copyright:
    tokuu@outlook.com